duckduckgo/duckduckgo-answerbar-templates

item/meanings_item.handlebars
This needs to be merged alongside that massive internal PR and this [other one](https://github.com/duckduckgo/duckduckgo-template-helpers/pull/1).
@bsstoner
=> trim -> stripNonAlpha

item/products_item.handlebars, shared/products_amazon_badge.handlebars
Requires an internal PR for the styling.  
Also requires https://github.com/duckduckgo/zeroclickinfo-spice/pull/2181
=> Amazon Prime Badge - Template Adjustment

item/news_item.handlebars, item/nlp_item.handlebars
Requires internal PR, don't merge yet
=> News Images

core/filter_dropdown.handlebars
See relevant internal PR.
@bsstoner
=> IA requery

item/news_item.handlebars, item/videos_item.handlebars
For News and Videos.
Requires an internal PR.
=> Wider Tile Variant

core/filter_dropdown.handlebars, core/metabar.handlebars
=> added specific container for filter dropdowns

core/metabar.handlebars, core/metabar_showing.handlebars
=> MetaBar updates

core/metabar.handlebars
=> Removed dropdown separator

core/metabar.handlebars
=> Hide primary text when loading

item/tiles_load_more.handlebars
This goes with a pending internal PR...
@bbraithwaite
=> Render loading gif as img

bower.json, core/filter_dropdown.handlebars, shared/attribution.handlebars, shared/attribution_modal.handlebars
Requires internal changes.
@andrey-p 
cc @bbraithwaite
=> Backport modal refactor from YHS

bower.json, core/filter_dropdown.handlebars, shared/attribution.handlebars, shared/attribution_modal.handlebars
=> YHS Changes

templates.js
Goes with internal PR
@andrey-p 
cc @moollaza
=> Add default template options

item/audio_item.handlebars
=> lazy load audio images

shared/play_button.handlebars
Part of an internal PR.
@bsstoner 
cc @moollaza
=> Play button fixes

shared/attribution_modal.handlebars
Added a `show` attribute to the developer data.
=> check show for each dev

detail/places_detail.handlebars
=> swap over 'get directions' for just 'directions'

item_detail/videos_detail.handlebars
Show the publishedDate icon if the date is available.
=> Wrap date icon in if statement

detail/info_detail.handlebars, item/categories_item.handlebars, item/meanings_item.handlebars, item/products_item.handlebars
This goes with another PR to duckduckgo/template-helpers.
@bbraithwaite 
cc @zachthompson @b2ddg @andrey-p
=> Pass explicit ellipsis value since default was removed

shared/no_results.handlebars
=> Allow custom no results message

item/news_item.handlebars
=> Use image in news tiles if it's passed in response

item_detail/images_detail.handlebars
=> Add background div for transparent images

item_detail/images_detail.handlebars
=> Link images in image detail pane

core/metabar.handlebars
=> Double wrap metabar dropdowns

item_detail/images_detail.handlebars
=> Remove linkImage conditional

item_detail/images_detail.handlebars
Need it for mobile, goes with an internal PR
@bbraithwaite
=> Revert removing linkImage conditional

item_detail/images_detail.handlebars
=> Changes to transparent background height/width

item_detail/images_detail.handlebars
=> Turn 'view file' link into a larger button

item/basic_image_item.handlebars, item/categories_item.handlebars, item/meanings_item.handlebars, item/videos_item.handlebars, shared/tile_titles.handlebars
=> Add title anchors

item/news_item.handlebars
cc @MariagraziaAlastra @bsstoner
=> Fix news item template

core/duckbar_tab.handlebars
Internal (cc @bbraithwaite @bsstoner)
=> Make sure late-rendering tabs will be displayed correctly

core/metabar.handlebars
=> Add option to always show secondaryText on small screens
